version: "3.5"

services:
    mysql:
        image: mariadb:10.9.3
        platform: linux/arm64/v8
        container_name: symfony-test-mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3306:3306'

    adminer:
        image: adminer
        container_name: symfony-test-adminer
        restart: always
        ports:
            - '8080:8080'

    web:
        build:
            context: ./
        container_name: symfony-test-web
        tty: true
        volumes:
            - './:/code'
        ports:
            - '8083:8000'

